name: not-w-my-name-env
channels:
  - pytorch
  - defaults
dependencies:
  - pip=22.3.1
  - pytorch=1.12.1
  - cudatoolkit=11.3.1
  - torchvision=0.13.1
  - pip:
      - absl-py==1.4.0
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - albumentations==1.3.0
      - async-timeout==4.0.2
      - asynctest==0.13.0
      - attrs==22.2.0
      - backcall==0.2.0
      - cachetools==5.3.0
      - cycler==0.11.0
      - decorator==5.1.1
      - filelock==3.9.0
      - fonttools==4.38.0
      - frozenlist==1.3.3
      - fsspec==2023.1.0
      - google-auth==2.16.0
      - google-auth-oauthlib==0.4.6
      - grpcio==1.51.1
      - huggingface-hub==0.12.0
      - imageio==2.25.0
      - importlib-metadata==6.0.0
      - ipython==7.34.0
      - jedi==0.18.2
      - joblib==1.2.0
      - kiwisolver==1.4.4
      - lightning-utilities==0.6.0.post0
      - markdown==3.4.1
      - markupsafe==2.1.2
      - matplotlib==3.5.3
      - matplotlib-inline==0.1.6
      - multidict==6.0.4
      - networkx==2.6.3
      - oauthlib==3.2.2
      - opencv-python-headless==4.7.0.68
      - packaging==23.0
      - pandas==1.3.5
      - parso==0.8.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - prompt-toolkit==3.0.36
      - protobuf==3.20.3
      - ptyprocess==0.7.0
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pygments==2.14.0
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - pytorch-lightning==1.9.1
      - pytz==2022.7.1
      - pywavelets==1.3.0
      - pyyaml==6.0
      - qudida==0.0.4
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scikit-image==0.19.3
      - scikit-learn==1.0.2
      - scipy==1.7.3
      - seaborn==0.12.2
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - threadpoolctl==3.1.0
      - tifffile==2021.11.2
      - timm==0.6.12
      - torch-tb-profiler==0.4.1
      - torchmetrics==0.11.1
      - tqdm==4.64.1
      - traitlets==5.9.0
      - wcwidth==0.2.6
      - werkzeug==2.2.2
      - yarl==1.8.2
      - zipp==3.13.0
